version: '3'
services:
  web:    
    build: ./web
    ports:
      - "3000:3000"
    links:
      - db
  db:    
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '123123'